"""Main converter class"""

import logging
from typing import List, Dict, Optional
from stix2suricata.core.parser import StixPatternParser
from stix2suricata.core.oca_parser import OCABundleParser
from stix2suricata.handlers.base import BaseHandler
from stix2suricata.utils.config import Config
from stix2suricata.handlers.network import NetworkHandler
from stix2suricata.handlers.domain import DomainHandler
from stix2suricata.handlers.url import URLHandler
from stix2suricata.handlers.http_body import HttpBodyHandler


class StixConverter:
    """Main converter class - orchestrates parsing and rule generation"""

    def __init__(self, config: Optional[Config] = None, starting_sid: int = -1):
        self.config = config or Config()
        self.parser = StixPatternParser()
        self.handlers: List[BaseHandler] = []
        self.logger = logging.getLogger(__name__)

        # SID management
        self.sid_counter = starting_sid if starting_sid >= 0 else self.config.get(
            'suricata.sid_start', 5000000)

    def register_handler(self, handler: BaseHandler):
        """Register a new indicator handler"""
        self.handlers.append(handler)
        self.logger.debug(f"Registered handler: {handler.__class__.__name__}")

    def register_default_handlers(self):
        """Register all default handlers"""

        self.register_handler(NetworkHandler(self.config))
        self.register_handler(DomainHandler(self.config))
        self.register_handler(URLHandler(self.config))
        self.register_handler(HttpBodyHandler(self.config))

    def get_next_sid(self) -> int:
        """Get next available SID"""
        sid = self.sid_counter
        self.sid_counter += 1
        return sid

    def convert_indicator(self, indicator: Dict) -> List[str]:
        """Convert a single indicator to Suricata rules"""
        rules = []

        for handler in self.handlers:
            if handler.can_handle(indicator['type']):
                self.logger.debug(
                    f"Handler {handler.__class__.__name__} processing {indicator['type']}")
                handler_rules = handler.handle(indicator, self.config)

                # Convert to rule strings with SIDs
                for rule in handler_rules:
                    sid = self.get_next_sid()
                    rule_str = rule.to_rule(sid)
                    rules.append(rule_str)

                break  # First handler wins
        else:
            self.logger.warning(
                f"No handler found for indicator type: {indicator['type']}")

        return rules

    def convert_pattern(self, pattern: str, metadata: Optional[Dict] = None) -> List[str]:
        """Convert STIX pattern to Suricata rules"""
        indicators = self.parser.parse(pattern)
        rules = []

        for indicator in indicators:
            if metadata:
                indicator['stix_metadata'] = metadata
            rule_strings = self.convert_indicator(indicator)
            rules.extend(rule_strings)

        return rules

    def convert_bundle(self, bundle: Dict) -> List[str]:
        """Convert STIX bundle to Suricata rules.

        Auto-detects OCA bundles (containing x-oca-detection objects)
        and routes them to OCABundleParser; standard STIX bundles use
        the regular StixPatternParser.
        """
        objects = bundle.get('objects', [])
        if any(o.get('type') == 'x-oca-detection' for o in objects):
            indicators = OCABundleParser().parse_bundle(bundle)
        else:
            indicators = self.parser.parse_bundle(bundle)

        rules = []
        for indicator in indicators:
            rule_strings = self.convert_indicator(indicator)
            rules.extend(rule_strings)

        return rules

    def save_rules(self, rules: List[str], filename: str, include_header: bool = True):
        """Save rules to file"""
        with open(filename, 'w') as f:
            if include_header:
                f.write("# Generated by STIX2Suricata\n")
                f.write(f"# Total rules: {len(rules)}\n")
                f.write("# \n")

            for rule in rules:
                f.write(rule + '\n')

        self.logger.info(f"Saved {len(rules)} rules to {filename}")
